version: "3.5"
volumes:
  volume_influxdb:
    external: true
  volume_grafana:
    external: true
  volume_portainer:
    external: true

services:
  influx:
    image: influxdb:2.0
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - volume_influxdb:/var/lib/influxdb2

  grafana:
    image: grafana/grafana:7.5.5
    restart: always
    environment:
      #- GF_INSTALL_PLUGINS=<plugins>
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - JEEDOM_DATASOURCE_BUCKET=${INFLUXDB_BUCKET}
      - JEEDOM_DATASOURCE_TOKEN=${READ_TOKEN}
    depends_on:
      - influx
    ports:
      - "3000:3000"
    volumes:
      - volume_grafana:/var/lib/grafana:rw
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources/

  portainer:
    image: portainer/portainer-ce
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - volume_portainer:/data
